### DISCUSSION TITLE
Domain Port Forward

### DISCUSSION THREAD

**Discussion by theobouwman** [timothystewart6/launchpad#29] [Questions]
I have my domain example.com pointed to my router. I pointed my ports 80 and 443 to the LoadBalancer IP:
```
service:
  enabled: true
  type: LoadBalancer
  annotations: {}
  labels: {}
  spec:
    loadBalancerIP: 192.168.178.89 # this should be an IP in the MetalLB range
  loadBalancerSourceRanges: []
  externalIPs: []
```

And when I run a curl:
```
$ curl 192.168.178.89                     
Moved Permanently%   
```
THis is the result

Because when I try to access treafik.example.com I get no result?
